### ISSUE TITLE
JSON ERROR

### ISSUE THREAD

**Issue by nessor** [carstenschwede/jeffrey.js#1]
JSON ERROR appears at 

node jeffrey.js -t MY_TEMP_DIRECTORY_PATH -w MY_WOLFRAM_ALPHA_KEY -l de

![bildschirmfoto 2015-09-20 um 12 27 14](https://cloud.githubusercontent.com/assets/3463261/9980294/fc6693e4-5f92-11e5-9254-9c799cf28bbf.png)

**Comment by carstenschwede** [comment]
I suggest to try [Jasper](https://github.com/jasperproject/jasper-client) as an alternative.
If you still need jeffrey.js, please post the output of:
`node -v`
`npm ls`

**Comment by nessor** [comment]
My Node Version is 0.12.6.

The Error appears only at -l de 

I will take a look at the Jasper project. Thanks

**Comment by mikejazz101** [comment]
Hi Carsten Schwede & Nessor,

I'm having issue as per-below. What I need to fix for jeffery run smoothly?
pi@raspberrypi:~/jeffrey $ node jeffrey.js -t /home/pi -w YOUR_WOLFRAM_ALPHA_KEY -l en 
Plugin loaded wikipedia
Plugin loaded wolfram
module.js:472
    throw err;
    ^

Error: Cannot find module './cleverbot'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/pi/jeffrey/ActionTemplates.js:2:18)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)

pi@raspberrypi:~/jeffrey $ node -v
v7.5.0

pi@raspberrypi:~/jeffrey $ npm ls
Jeffrey@0.0.0 /home/pi/jeffrey
├── async@0.2.10
├─┬ optimist@0.6.1
│ ├── minimist@0.0.10
│ └── wordwrap@0.0.3
├─┬ request@2.27.0
│ ├── aws-sign@0.3.0
│ ├── cookie-jar@0.3.0
│ ├── forever-agent@0.5.2
│ ├─┬ form-data@0.1.4
│ │ ├── async@0.9.2
│ │ └─┬ combined-stream@0.0.7
│ │   └── delayed-stream@0.0.5
│ ├─┬ hawk@1.0.0
│ │ ├── boom@0.4.2
│ │ ├── cryptiles@0.2.2
│ │ ├── hoek@0.9.1
│ │ └── sntp@0.2.4
│ ├─┬ http-signature@0.10.1
│ │ ├── asn1@0.1.11
│ │ ├── assert-plus@0.1.5
│ │ └── ctype@0.5.3
│ ├── json-stringify-safe@5.0.1
│ ├── mime@1.2.11
│ ├── node-uuid@1.4.7
│ ├── oauth-sign@0.3.0
│ ├── qs@0.6.6
│ └── tunnel-agent@0.3.0
└─┬ wolfram-alpha@0.5.0
  ├─┬ libxmljs@0.18.4
  │ ├── bindings@1.2.1
  │ ├── nan@2.5.1
  │ └─┬ node-pre-gyp@0.6.33
  │   ├─┬ mkdirp@0.5.1
  │   │ └── minimist@0.0.8
  │   ├─┬ nopt@3.0.6
  │   │ └── abbrev@1.0.9
  │   ├─┬ npmlog@4.0.2
  │   │ ├─┬ are-we-there-yet@1.1.2
  │   │ │ ├── delegates@1.0.0
  │   │ │ └── readable-stream@2.2.2
  │   │ ├── console-control-strings@1.1.0
  │   │ ├─┬ gauge@2.7.3
  │   │ │ ├── aproba@1.1.0
  │   │ │ ├── has-unicode@2.0.1
  │   │ │ ├── object-assign@4.1.1
  │   │ │ ├── signal-exit@3.0.2
  │   │ │ ├─┬ string-width@1.0.2
  │   │ │ │ ├── code-point-at@1.1.0
  │   │ │ │ └─┬ is-fullwidth-code-point@1.0.0
  │   │ │ │   └── number-is-nan@1.0.1
  │   │ │ └── wide-align@1.1.0
  │   │ └── set-blocking@2.0.0
  │   ├─┬ rc@1.1.6
  │   │ ├── deep-extend@0.4.1
  │   │ ├── ini@1.3.4
  │   │ ├── minimist@1.2.0
  │   │ └── strip-json-comments@1.0.4
  │   ├─┬ request@2.79.0
  │   │ ├─┬ combined-stream@1.0.5
  │   │ │ └── delayed-stream@1.0.0
  │   │ ├── forever-agent@0.6.1
  │   │ ├── form-data@2.1.2
  │   │ ├─┬ hawk@3.1.3
  │   │ │ ├── boom@2.10.1
  │   │ │ ├── cryptiles@2.0.5
  │   │ │ ├── hoek@2.16.3
  │   │ │ └── sntp@1.0.9
  │   │ ├─┬ http-signature@1.1.1
  │   │ │ └── assert-plus@0.2.0
  │   │ ├── oauth-sign@0.8.2
  │   │ ├── qs@6.3.0
  │   │ ├── tunnel-agent@0.4.3
  │   │ └── uuid@3.0.1
  │   ├─┬ rimraf@2.5.4
  │   │ └─┬ glob@7.1.1
  │   │   ├── fs.realpath@1.0.0
  │   │   ├── inflight@1.0.6
  │   │   ├─┬ minimatch@3.0.3
  │   │   │ └─┬ brace-expansion@1.1.6
  │   │   │   ├── balanced-match@0.4.2
  │   │   │   └── concat-map@0.0.1
  │   │   ├── once@1.4.0
  │   │   └── path-is-absolute@1.0.1
  │   ├── semver@5.3.0
  │   ├─┬ tar@2.2.1
  │   │ ├── block-stream@0.0.9
  │   │ ├─┬ fstream@1.0.10
  │   │ │ └── graceful-fs@4.1.11
  │   │ └── inherits@2.0.3
  │   └─┬ tar-pack@3.3.0
  │     ├─┬ debug@2.2.0
  │     │ └── ms@0.7.1
  │     ├── fstream-ignore@1.0.5
  │     ├─┬ once@1.3.3
  │     │ └── wrappy@1.0.2
  │     ├─┬ readable-stream@2.1.5
  │     │ ├── buffer-shims@1.0.0
  │     │ ├── core-util-is@1.0.2
  │     │ ├── isarray@1.0.0
  │     │ ├── process-nextick-args@1.0.7
  │     │ ├── string_decoder@0.10.31
  │     │ └── util-deprecate@1.0.2
  │     └── uid-number@0.0.6
  └─┬ request@2.79.0
    ├── aws-sign2@0.6.0
    ├── aws4@1.6.0
    ├── caseless@0.11.0
    ├─┬ combined-stream@1.0.5
    │ └── delayed-stream@1.0.0
    ├── extend@3.0.0
    ├── forever-agent@0.6.1
    ├─┬ form-data@2.1.2
    │ └── asynckit@0.4.0
    ├─┬ har-validator@2.0.6
    │ ├─┬ chalk@1.1.3
    │ │ ├── ansi-styles@2.2.1
    │ │ ├── escape-string-regexp@1.0.5
    │ │ ├─┬ has-ansi@2.0.0
    │ │ │ └── ansi-regex@2.1.1
    │ │ ├── strip-ansi@3.0.1
    │ │ └── supports-color@2.0.0
    │ ├─┬ commander@2.9.0
    │ │ └── graceful-readlink@1.0.1
    │ ├─┬ is-my-json-valid@2.15.0
    │ │ ├── generate-function@2.0.0
    │ │ ├─┬ generate-object-property@1.2.0
    │ │ │ └── is-property@1.0.2
    │ │ ├── jsonpointer@4.0.1
    │ │ └── xtend@4.0.1
    │ └─┬ pinkie-promise@2.0.1
    │   └── pinkie@2.0.4
    ├─┬ hawk@3.1.3
    │ ├── boom@2.10.1
    │ ├── cryptiles@2.0.5
    │ ├── hoek@2.16.3
    │ └── sntp@1.0.9
    ├─┬ http-signature@1.1.1
    │ ├── assert-plus@0.2.0
    │ ├─┬ jsprim@1.3.1
    │ │ ├── extsprintf@1.0.2
    │ │ ├── json-schema@0.2.3
    │ │ └── verror@1.3.6
    │ └─┬ sshpk@1.10.2
    │   ├── asn1@0.2.3
    │   ├── assert-plus@1.0.0
    │   ├── bcrypt-pbkdf@1.0.1
    │   ├─┬ dashdash@1.14.1
    │   │ └── assert-plus@1.0.0
    │   ├── ecc-jsbn@0.1.1
    │   ├─┬ getpass@0.1.6
    │   │ └── assert-plus@1.0.0
    │   ├── jodid25519@1.0.2
    │   ├── jsbn@0.1.0
    │   └── tweetnacl@0.14.5
    ├── is-typedarray@1.0.0
    ├── isstream@0.1.2
    ├─┬ mime-types@2.1.14
    │ └── mime-db@1.26.0
    ├── oauth-sign@0.8.2
    ├── qs@6.3.0
    ├── stringstream@0.0.5
    ├─┬ tough-cookie@2.3.2
    │ └── punycode@1.4.1
    ├── tunnel-agent@0.4.3
    └── uuid@3.0.1
